# Site settings
title: Andy English Chat Robot
header-img: img/home-bg.jpg
email: andyenglishbot@gmail.com
description: Chat in English with Friendly Robot Andy. English Practice, Grammar, Speaking. Andy English Bot is the best chatbot for learning English. Available on Facebook Messenger, iOS and Telegram

url: "http://andychatbot.com"
facebook_username: chatbotandy

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","README.md"]
