# Site settings
title: Sublime Meditation Timer
header-img: img/home-bg.jpg
email: sublimetimer@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"

url: "http://sublimetimer.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
