# Site settings
title: Andy English Bot - Chat and Learn English with Robot
header-img: img/home-bg.jpg
email: contact@andychatbot.com
description: Chat in English with Robot Andy. English Practice, Grammar, Speaking. Andy English Bot is the best chatbot for learning English. Talk on Facebook Messenger, iOS and Telegram
keywords: "andy, andy bot, english andy, andy english, andyrobot, andy english speaking bot, andy chatbot, chatbot andy"

url: "https://andychatbot.com"
facebook_username: chatbotandy

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","README.md"]
include: ['.well-known']