# Site settings
title: Sublime Meditation Timer
header-img: img/home-bg.jpg
email: sublimetimer@gmail.com
description: The best meditation timer and tracker

url: "http://sublimetimer.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","README.md"]
