# Site settings
title: Sublime Meditation Timer App
header-img: img/home-bg.jpg
email: sublimetimer@gmail.com
description: The best meditation timer and tracker application for iOS

url: "http://sublimetimer.com"
facebook_username: sublimetimer
twitter_username: sublimetimer
pinterest_username: sublimetimer

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","README.md"]
