# Site settings
title: Andy English Chat Robot
header-img: img/home-bg.jpg
email: andyenglishbot@gmail.com
description: Chat in English with Friendly Robot Andy, English Practice, Grammar, Speaking. Best chatbot for learning English

url: "http://andychatbot.com"
facebook_username: chatbotandy

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","README.md"]
