# Site settings
title: Andy English Chat Robot
header-img: img/home-bg.jpg
email: andyenglishbot@gmail.com
description: Chat in English with Friendly Robot Andy, English Practice, Grammar, Speaking

url: "http://andychatbot.com"
facebook_username: chatbotandy
twitter_username: andychatbot

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","README.md"]
